# /// script
# requires-python = ">=3.14"
# dependencies = [
#   "cyclopts",
#   "niquests",
#   "professor-pendo @ git+https://github.com/boonhapus/professor-pendo",
#   "python-dotenv",
#   "structlog",
# ]
# ///
"""
Rebuild pendo-docs skill reference files from live documentation sources.

Run periodically (e.g. weekly via cron or CI) to keep the agent's doc index current.
Each source writes its own Markdown file into the skill's references/ folder.

Usage (from professor-pendo repo root, after `uv sync`):

    uv run .agents/SKILLS/pendo/pendo-docs/scripts/refresh_docs.py
    uv run .agents/SKILLS/pendo/pendo-docs/scripts/refresh_docs.py --source help-center

If you need the local `professor_pendo` package (unpublished edits), add `--with-editable .`
before the script path.
"""

from __future__ import annotations

import datetime as dt
import pathlib
import xml.etree.ElementTree as ET
from typing import Annotated, Literal

from cyclopts import App, Parameter
from professor_pendo import types, utils
import dotenv
import niquests
import structlog

LOGGER = structlog.get_logger(__name__)

app = App(
    name="refresh-docs",
    help="Rebuild pendo-docs skill reference files from live documentation sources.",
)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

SCRIPT_DIR  = pathlib.Path(__file__).parent
REFS_DIR    = SCRIPT_DIR.parent / "references"

SOURCE_FILES: dict[str, pathlib.Path] = {
    "help-center": REFS_DIR / "help-center.md",
    "web-sdk":     REFS_DIR / "web-sdk.md",
    "engage-api":  REFS_DIR / "engage-api.md",
    "mobile-sdk":  REFS_DIR / "mobile-sdk.md",
}

SourceT = Literal["all", "help-center", "web-sdk", "engage-api", "mobile-sdk"]

# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def _header(source: str, fetched_from: str) -> str:
    """Standard frontmatter block for every reference file."""
    ts = dt.datetime.now(dt.UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    return (
        f"<!-- AUTO-GENERATED by refresh_docs.py — do not edit by hand -->\n"
        f"<!-- source: {fetched_from} -->\n"
        f"<!-- refreshed: {ts} -->\n\n"
    )


def _write(path: pathlib.Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    LOGGER.info("wrote_reference_file", path=str(path), bytes=len(content))


# ---------------------------------------------------------------------------
# Source: Help Center  (sitemap.xml → grouped article index)
# ---------------------------------------------------------------------------

SITEMAP_URL  = "https://support.pendo.io/hc/sitemap.xml"
SITEMAP_NS   = {"sm": "http://www.sitemaps.org/schemas/sitemap/0.9"}

# Map URL path prefixes → section labels
_HC_SECTIONS: list[tuple[str, str]] = [
    ("/hc/en-us/articles/",   "Articles"),
    ("/hc/en-us/sections/",   "Sections"),
    ("/hc/en-us/categories/", "Categories"),
    ("/hc/en-us/community/",  "Community Posts"),
]


def _slug_to_title(slug: str) -> str:
    """Best-effort: turn a URL slug into a readable title.

    Zendesk slugs look like:  19310195851931-Opt-out-of-tracking-with-DNP
    Strip the leading numeric ID and replace hyphens with spaces.
    """
    # drop leading digits + first hyphen (the article ID)
    parts = slug.split("-", 1)
    text = parts[1] if len(parts) == 2 and parts[0].isdigit() else slug
    return text.replace("-", " ").strip()


async def _refresh_help_center(client: niquests.AsyncSession) -> str:
    await LOGGER.ainfo("refreshing_help_center", url=SITEMAP_URL)

    r = await client.get(SITEMAP_URL)
    r.raise_for_status()

    root = ET.fromstring(r.text)
    urls: list[str] = [
        loc.text.strip()
        for loc in root.findall(".//sm:loc", SITEMAP_NS)
        if loc.text
    ]

    await LOGGER.ainfo("sitemap_parsed", total_urls=len(urls))

    # Bucket URLs by section
    buckets: dict[str, list[tuple[str, str]]] = {label: [] for _, label in _HC_SECTIONS}
    uncategorised: list[str] = []

    for url in urls:
        path = url.replace("https://support.pendo.io", "")
        matched = False
        for prefix, label in _HC_SECTIONS:
            if prefix in path:
                slug = path.rstrip("/").rsplit("/", 1)[-1]
                title = _slug_to_title(slug)
                buckets[label].append((title, url))
                matched = True
                break
        if not matched:
            uncategorised.append(url)

    # Build Markdown
    lines: list[str] = [
        "# Pendo Help Center — Article Index\n",
        f"> **{len(urls)} URLs** indexed from `{SITEMAP_URL}`\n",
        "> Fetch any URL directly with `web_fetch` — the Help Center blocks index pages but individual articles load fine.\n\n",
        "## How to use this index\n",
        "Search this file for keywords matching the user's question, pick the closest URL, then call `web_fetch` on it.\n\n",
    ]

    for _, label in _HC_SECTIONS:
        entries = buckets[label]
        if not entries:
            continue
        lines.append(f"## {label} ({len(entries)})\n\n")
        for title, url in sorted(entries, key=lambda x: x[0].lower()):
            lines.append(f"- [{title}]({url})\n")
        lines.append("\n")

    if uncategorised:
        lines.append(f"## Other ({len(uncategorised)})\n\n")
        for url in sorted(uncategorised):
            lines.append(f"- {url}\n")
        lines.append("\n")

    return _header("Help Center", SITEMAP_URL) + "".join(lines)


# ---------------------------------------------------------------------------
# Source: Web SDK  (crawl known sitemap + extract nav links)
# ---------------------------------------------------------------------------

WEB_SDK_ROOT    = "https://web-sdk.pendo.io"
WEB_SDK_SITEMAP = f"{WEB_SDK_ROOT}/sitemap.xml"

# Fallback known paths if the sitemap is unavailable
_WEB_SDK_KNOWN: list[tuple[str, str]] = [
    ("/",                          "Overview — installation, builds, debugging"),
    ("/config/",                   "Configuration — all initialize() options"),
    ("/config/analytics",          "Analytics config"),
    ("/config/core",               "Core config — apiKey, visitor, account"),
    ("/config/guides",             "Guides config — delay, timeout, globalScripts"),
    ("/config/network-logs",       "Network log capture config"),
    ("/config/replay",             "Session Replay config"),
    ("/events/browser-events",     "Browser events emitted by the SDK"),
    ("/public/classic-guides",     "Public functions — pendo.track(), pendo.identify(), etc."),
    ("/cookies/localstorage",      "Cookie and localStorage usage"),
    ("/advanced/auto-frame-install", "Advanced — iframes, auto-install"),
    ("/releases",                  "Release history — beta and stable tracks"),
    ("/versions",                  "Version notes"),
]


async def _refresh_web_sdk(client: niquests.AsyncSession) -> str:
    await LOGGER.ainfo("refreshing_web_sdk", url=WEB_SDK_SITEMAP)

    pages: list[tuple[str, str]] = []  # (path, description)

    # Try sitemap first
    try:
        r = await client.get(WEB_SDK_SITEMAP, timeout=10)
        r.raise_for_status()
        root = ET.fromstring(r.text)
        raw_urls = [
            loc.text.strip()
            for loc in root.findall(".//sm:loc", SITEMAP_NS)
            if loc.text
        ]
        for url in raw_urls:
            path = url.replace(WEB_SDK_ROOT, "") or "/"
            pages.append((path, ""))
        await LOGGER.ainfo("web_sdk_sitemap_ok", pages=len(pages))
    except Exception:
        await LOGGER.awarning("web_sdk_sitemap_unavailable", fallback="known page list")
        pages = _WEB_SDK_KNOWN

    lines: list[str] = [
        "# Pendo Web SDK — Page Index\n\n",
        f"> All pages are directly fetchable from `{WEB_SDK_ROOT}<path>`.\n\n",
        "## Pages\n\n",
    ]

    for path, desc in sorted(pages, key=lambda x: x[0]):
        url = f"{WEB_SDK_ROOT}{path}"
        label = desc if desc else path
        lines.append(f"- [{label}]({url})\n")

    lines.append("\n## Key public functions\n\n")
    lines.append(
        "Documented under `/public/` — use `web_fetch` on the index page to find individual function pages.\n\n"
        "| Function | Purpose |\n"
        "|---|---|\n"
        "| `pendo.initialize(config)` | Bootstrap the SDK with visitor/account/config |\n"
        "| `pendo.identify(visitor, account)` | Update visitor or account metadata mid-session |\n"
        "| `pendo.track(event, properties)` | Send a custom track event |\n"
        "| `pendo.showGuideById(id)` | Programmatically show a specific guide |\n"
        "| `pendo.stopGuides()` | Prevent any guide from rendering |\n"
        "| `pendo.enableDebugging()` | Activate the SDK debugger in the browser console |\n"
        "| `pendo.getActiveGuides()` | Return list of currently active guides |\n"
    )

    return _header("Web SDK", WEB_SDK_SITEMAP) + "".join(lines)


# ---------------------------------------------------------------------------
# Source: Engage API  (fetch OpenAPI/Swagger spec or root page)
# ---------------------------------------------------------------------------

ENGAGE_API_ROOT    = "https://engageapi.pendo.io"
ENGAGE_API_SPEC    = f"{ENGAGE_API_ROOT}/swagger.json"

# Known top-level resource groups
_API_RESOURCES: list[tuple[str, str]] = [
    ("Aggregation",       "POST /api/v1/aggregation — analytics query pipeline"),
    ("Features",          "CRUD for feature tag definitions"),
    ("Pages",             "CRUD for page tag definitions"),
    ("Guides",            "CRUD for in-app guides"),
    ("Track Events",      "Custom track event ingestion and retrieval"),
    ("Visitor Metadata",  "Read/write visitor metadata fields"),
    ("Account Metadata",  "Read/write account metadata fields"),
    ("NPS / Polls",       "NPS poll responses and metadata"),
    ("Reports",           "Saved report definitions"),
    ("Subscription",      "Subscription-level settings"),
]


async def _refresh_engage_api(client: niquests.AsyncSession) -> str:
    await LOGGER.ainfo("refreshing_engage_api", url=ENGAGE_API_ROOT)

    spec_note = ""
    try:
        r = await client.get(ENGAGE_API_SPEC, timeout=10)
        r.raise_for_status()
        spec = r.json()
        paths = list(spec.get("paths", {}).keys())
        await LOGGER.ainfo("engage_api_spec_ok", paths=len(paths))
        spec_note = f"> OpenAPI spec fetched: **{len(paths)} endpoints** found.\n\n"
    except Exception:
        await LOGGER.awarning("engage_api_spec_unavailable", fallback="known resource list")
        paths = []
        spec_note = f"> OpenAPI spec unavailable — using known resource summary. Fetch `{ENGAGE_API_SPEC}` for full endpoint details.\n\n"

    lines: list[str] = [
        "# Pendo Engage API — Endpoint Reference\n\n",
        f"> Root: `{ENGAGE_API_ROOT}` — Swagger UI with interactive docs.\n",
        spec_note,
        "## Authentication\n\n",
        "All requests require an `x-pendo-integration-key` header containing a Pendo integration key.\n",
        "Base URL varies by region:\n\n",
        "| Region | Base URL |\n",
        "|---|---|\n",
        "| US (default) | `https://app.pendo.io` |\n",
        "| EU | `https://app.eu.pendo.io` |\n",
        "| US1 | `https://us1.app.pendo.io` |\n",
        "| Japan | `https://app.jpn.pendo.io` |\n\n",
    ]

    if paths:
        lines.append("## Endpoints\n\n")
        for path in sorted(paths):
            lines.append(f"- `{path}`\n")
        lines.append("\n")
    else:
        lines.append("## Resource Groups\n\n")
        for resource, desc in _API_RESOURCES:
            lines.append(f"- **{resource}** — {desc}\n")
        lines.append("\n")

    lines.append(
        "## Key endpoints (always available)\n\n"
        "| Purpose | Method + Path |\n"
        "|---|---|\n"
        "| Analytics query | `POST /api/v1/aggregation` |\n"
        "| Set visitor DNP | `PUT /api/v1/metadata/visitor/pendo/value/{id}/donotprocess` |\n"
        "| Set account DNP | `PUT /api/v1/metadata/account/pendo/value/{id}/donotprocess` |\n"
        "| Get visitor metadata schema | `GET /api/v1/metadata/schema/visitor` |\n"
        "| Get account metadata schema | `GET /api/v1/metadata/schema/account` |\n"
        "| Bulk delete visitors/accounts | `DELETE /api/v1/entities/{kind}` |\n"
        "| List guides | `GET /api/v1/guide` |\n"
        "| Get guide by ID | `GET /api/v1/guide/{id}` |\n"
    )

    return _header("Engage API", ENGAGE_API_ROOT) + "".join(lines)


# ---------------------------------------------------------------------------
# Source: Mobile SDK  (GitHub repo tree via API)
# ---------------------------------------------------------------------------

MOBILE_SDK_REPO = "pendo-io/pendo-mobile-sdk"
GITHUB_TREE_URL = f"https://api.github.com/repos/{MOBILE_SDK_REPO}/git/trees/master?recursive=1"
MOBILE_SDK_URL  = f"https://github.com/{MOBILE_SDK_REPO}"

# Platforms we expect to find in the repo
_PLATFORMS: list[str] = ["iOS", "Android", "ReactNative", "Flutter", "Xamarin", "Cordova"]


async def _refresh_mobile_sdk(client: niquests.AsyncSession) -> str:
    await LOGGER.ainfo("refreshing_mobile_sdk", url=MOBILE_SDK_URL)

    tree_items: list[str] = []
    tree_note = ""

    try:
        r = await client.get(GITHUB_TREE_URL, timeout=15)
        r.raise_for_status()
        data = r.json()
        tree_items = [item["path"] for item in data.get("tree", []) if item.get("type") == "blob"]
        await LOGGER.ainfo("mobile_sdk_tree_ok", files=len(tree_items))
    except Exception:
        await LOGGER.awarning("mobile_sdk_tree_unavailable", fallback="known platform list")
        tree_note = "> GitHub tree API unavailable — using known platform summary.\n\n"

    lines: list[str] = [
        "# Pendo Mobile SDK — Repository Index\n\n",
        f"> Repository: `{MOBILE_SDK_URL}`\n",
        tree_note or f"> **{len(tree_items)} files** indexed from the GitHub tree API.\n\n",
        "## Installation entry point\n\n",
        f"- [README.md]({MOBILE_SDK_URL}/blob/master/README.md)\n\n",
        "## Platforms\n\n",
    ]

    if tree_items:
        # Group files by top-level directory (platform)
        buckets: dict[str, list[str]] = {}
        for path in sorted(tree_items):
            top = path.split("/")[0] if "/" in path else ""
            buckets.setdefault(top, []).append(path)

        for platform in _PLATFORMS:
            files = buckets.get(platform, [])
            if not files:
                continue
            lines.append(f"### {platform} ({len(files)} files)\n\n")
            # Surface only READMEs and key integration files to keep the index readable
            key_files = [f for f in files if "README" in f.upper() or f.endswith((".md", ".podspec", ".gradle", ".json"))]
            for f in key_files[:10]:
                url = f"{MOBILE_SDK_URL}/blob/master/{f}"
                lines.append(f"- [{f}]({url})\n")
            if len(files) > len(key_files):
                lines.append(f"- *(+ {len(files) - len(key_files)} more source files)*\n")
            lines.append("\n")

        # Anything not in a known platform
        other = {k: v for k, v in buckets.items() if k not in _PLATFORMS and k}
        if other:
            lines.append("### Other top-level files\n\n")
            for path in sorted(f for files in other.values() for f in files)[:20]:
                url = f"{MOBILE_SDK_URL}/blob/master/{path}"
                lines.append(f"- [{path}]({url})\n")
            lines.append("\n")
    else:
        for platform in _PLATFORMS:
            lines.append(
                f"### {platform}\n\n"
                f"- [README]({MOBILE_SDK_URL}/blob/master/{platform}/README.md)\n\n"
            )

    return _header("Mobile SDK", MOBILE_SDK_URL) + "".join(lines)


# ---------------------------------------------------------------------------
# Dispatch table
# ---------------------------------------------------------------------------

_REFRESHERS = {
    "help-center": _refresh_help_center,
    "web-sdk":     _refresh_web_sdk,
    "engage-api":  _refresh_engage_api,
    "mobile-sdk":  _refresh_mobile_sdk,
}


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

@app.default
async def main(
    *,
    source: Annotated[
        SourceT,
        Parameter(help="Which documentation source to refresh. Defaults to 'all'."),
    ] = "all",
) -> types.ExitCodeT:
    targets = list(_REFRESHERS.keys()) if source == "all" else [source]

    await LOGGER.ainfo("refresh_start", targets=targets)

    async with niquests.AsyncSession() as client:
        exit_code: types.ExitCodeT = 0

        for target in targets:
            refresher = _REFRESHERS[target]
            out_path = SOURCE_FILES[target]

            try:
                content = await refresher(client)
                _write(out_path, content)
                await LOGGER.ainfo("source_ok", source=target)
            except niquests.HTTPError:
                await LOGGER.aerror("source_http_error", source=target, exc_info=True)
                exit_code = 1
            except Exception:
                await LOGGER.aerror("source_unexpected_error", source=target, exc_info=True)
                exit_code = 1

    await LOGGER.ainfo("refresh_done", exit_code=exit_code)
    return exit_code


if __name__ == "__main__":
    utils.setup_logging()
    dotenv.load_dotenv()
    raise SystemExit(app())
